"""Ingest a local folder of markdown notes into lnclite."""

import asyncio
import shutil
from pathlib import Path

from openai import AsyncOpenAI
from openai_embeddings_model import ModelSettings

from lnclite import Lnclite, get_openai_embeddings_model
from lnclite.examples.sample_data import write_sample_notes

SOURCE_DIR = Path("outputs/examples/source-notes")
STORE_PATH = Path("outputs/examples/directory-ingest.lance")


async def main() -> None:
    if STORE_PATH.exists():
        shutil.rmtree(STORE_PATH)
    if SOURCE_DIR.exists():
        shutil.rmtree(SOURCE_DIR)

    note_paths = write_sample_notes(SOURCE_DIR)

    embeddings = get_openai_embeddings_model(openai_client=AsyncOpenAI())
    client = await Lnclite.new_from_dir(
        dir_path=SOURCE_DIR,
        lancedb_path=STORE_PATH,
        dataset_name="Directory ingest",
        dataset_description="Markdown notes generated by the directory example.",
        openai_embeddings_model=embeddings,
        model_settings=ModelSettings(dimensions=1536),
    )

    try:
        results = await client.search("What should I check before a release?", limit=3)
        print("Search results:")
        for result in results.results:
            print(f"- {result.document.content.splitlines()[0]}")
            print(f"  tags: {', '.join(result.document.tags)}")

        path_tag = f"path:{note_paths[-1].relative_to(SOURCE_DIR).as_posix()}"
        page = await client.documents.list(tags_all=[path_tag], limit=5)
        print(f"\nDocuments with {path_tag}:")
        for document in page.data:
            print(f"- {document.content.splitlines()[0]}")
    finally:
        await client.close()


if __name__ == "__main__":
    asyncio.run(main())
